use std::collections::{BTreeMap, BTreeSet};

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(super) struct LanguageSpec {
    pub(super) id: &'static str,
    pub(super) name: &'static str,
    pub(super) command: &'static [&'static str],
    pub(super) extensions: &'static [&'static str],
    pub(super) markers: &'static [&'static str],
    pub(super) workspace_symbols: bool,
    pub(super) hover: bool,
    pub(super) definition: bool,
    pub(super) references: bool,
    pub(super) implementation: bool,
    pub(super) call_hierarchy: bool,
    pub(super) diagnostics: bool,
    pub(super) document_symbols: bool,
    pub(super) rename: bool,
}

#[derive(Clone, Debug, Default)]
pub(super) struct WorkspaceScan {
    pub(super) files: usize,
    pub(super) extensions: BTreeMap<String, usize>,
    pub(super) markers: BTreeSet<String>,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(super) enum LspOperation {
    WorkspaceSymbols,
    Completion,
    Hover,
    Definition,
    References,
    Implementation,
    CallHierarchy,
    Diagnostics,
    DocumentSymbols,
    Formatting,
    CodeActions,
    Rename,
}

pub(super) const LANGUAGE_SPECS: &[LanguageSpec] = &[
    LanguageSpec {
        id: "rust",
        name: "Rust",
        command: &["rust-analyzer"],
        extensions: &["rs"],
        markers: &["Cargo.toml", "rust-project.json"],
        workspace_symbols: true,
        hover: true,
        definition: true,
        references: true,
        implementation: true,
        call_hierarchy: true,
        diagnostics: true,
        document_symbols: true,
        rename: true,
    },
    LanguageSpec {
        id: "typescript",
        name: "TypeScript",
        command: &["typescript-language-server", "--stdio"],
        extensions: &["ts", "tsx", "mts", "cts"],
        markers: &["tsconfig.json", "package.json", "deno.json", "deno.jsonc"],
        workspace_symbols: true,
        hover: true,
        definition: true,
        references: true,
        implementation: true,
        call_hierarchy: true,
        diagnostics: true,
        document_symbols: true,
        rename: true,
    },
    LanguageSpec {
        id: "javascript",
        name: "JavaScript",
        command: &["typescript-language-server", "--stdio"],
        extensions: &["js", "jsx", "mjs", "cjs"],
        markers: &["package.json", "jsconfig.json"],
        workspace_symbols: true,
        hover: true,
        definition: true,
        references: true,
        implementation: true,
        call_hierarchy: true,
        diagnostics: true,
        document_symbols: true,
        rename: true,
    },
    LanguageSpec {
        id: "python",
        name: "Python",
        command: &["pyright-langserver", "--stdio"],
        extensions: &["py", "pyi"],
        markers: &[
            "pyproject.toml",
            "requirements.txt",
            "setup.py",
            "poetry.lock",
            "Pipfile",
        ],
        workspace_symbols: true,
        hover: true,
        definition: true,
        references: true,
        implementation: true,
        call_hierarchy: true,
        diagnostics: true,
        document_symbols: true,
        rename: true,
    },
    LanguageSpec {
        id: "go",
        name: "Go",
        command: &["gopls"],
        extensions: &["go"],
        markers: &["go.mod", "go.work"],
        workspace_symbols: true,
        hover: true,
        definition: true,
        references: true,
        implementation: true,
        call_hierarchy: true,
        diagnostics: true,
        document_symbols: true,
        rename: true,
    },
    LanguageSpec {
        id: "c_cpp",
        name: "C/C++",
        command: &["clangd"],
        extensions: &["c", "cc", "cpp", "cxx", "h", "hpp", "hh", "hxx"],
        markers: &["compile_commands.json", "CMakeLists.txt"],
        workspace_symbols: true,
        hover: true,
        definition: true,
        references: true,
        implementation: true,
        call_hierarchy: true,
        diagnostics: true,
        document_symbols: true,
        rename: true,
    },
    LanguageSpec {
        id: "java",
        name: "Java",
        command: &["jdtls"],
        extensions: &["java"],
        markers: &[
            "pom.xml",
            "build.gradle",
            "build.gradle.kts",
            "settings.gradle",
        ],
        workspace_symbols: true,
        hover: true,
        definition: true,
        references: true,
        implementation: true,
        call_hierarchy: true,
        diagnostics: true,
        document_symbols: true,
        rename: true,
    },
    LanguageSpec {
        id: "csharp",
        name: "C#",
        command: &["omnisharp"],
        extensions: &["cs", "csx"],
        markers: &["global.json", ".sln", ".csproj"],
        workspace_symbols: true,
        hover: true,
        definition: true,
        references: true,
        implementation: true,
        call_hierarchy: true,
        diagnostics: true,
        document_symbols: true,
        rename: true,
    },
    LanguageSpec {
        id: "ruby",
        name: "Ruby",
        command: &["solargraph", "stdio"],
        extensions: &["rb"],
        markers: &["Gemfile", ".ruby-version"],
        workspace_symbols: true,
        hover: true,
        definition: true,
        references: true,
        implementation: true,
        call_hierarchy: true,
        diagnostics: true,
        document_symbols: true,
        rename: true,
    },
    LanguageSpec {
        id: "lua",
        name: "Lua",
        command: &["lua-language-server"],
        extensions: &["lua"],
        markers: &[".luarc.json", ".luarc.jsonc"],
        workspace_symbols: true,
        hover: true,
        definition: true,
        references: true,
        implementation: true,
        call_hierarchy: true,
        diagnostics: true,
        document_symbols: true,
        rename: true,
    },
    LanguageSpec {
        id: "bash",
        name: "Bash",
        command: &["bash-language-server", "start"],
        extensions: &["sh", "bash", "zsh"],
        markers: &[".git"],
        workspace_symbols: true,
        hover: true,
        definition: true,
        references: true,
        implementation: false,
        call_hierarchy: false,
        diagnostics: true,
        document_symbols: true,
        rename: true,
    },
    LanguageSpec {
        id: "json",
        name: "JSON",
        command: &["vscode-json-language-server", "--stdio"],
        extensions: &["json", "jsonc"],
        markers: &[".git"],
        workspace_symbols: false,
        hover: true,
        definition: false,
        references: false,
        implementation: false,
        call_hierarchy: false,
        diagnostics: true,
        document_symbols: true,
        rename: false,
    },
    LanguageSpec {
        id: "yaml",
        name: "YAML",
        command: &["yaml-language-server", "--stdio"],
        extensions: &["yaml", "yml"],
        markers: &[".git"],
        workspace_symbols: false,
        hover: true,
        definition: true,
        references: false,
        implementation: false,
        call_hierarchy: false,
        diagnostics: true,
        document_symbols: true,
        rename: false,
    },
    LanguageSpec {
        id: "toml",
        name: "TOML",
        command: &["taplo", "lsp", "stdio"],
        extensions: &["toml"],
        markers: &[".git"],
        workspace_symbols: false,
        hover: true,
        definition: false,
        references: false,
        implementation: false,
        call_hierarchy: false,
        diagnostics: true,
        document_symbols: true,
        rename: false,
    },
    LanguageSpec {
        id: "html",
        name: "HTML",
        command: &["vscode-html-language-server", "--stdio"],
        extensions: &["html", "htm"],
        markers: &["package.json", ".git"],
        workspace_symbols: false,
        hover: true,
        definition: true,
        references: false,
        implementation: false,
        call_hierarchy: false,
        diagnostics: true,
        document_symbols: true,
        rename: true,
    },
    LanguageSpec {
        id: "css",
        name: "CSS",
        command: &["vscode-css-language-server", "--stdio"],
        extensions: &["css", "scss", "less"],
        markers: &["package.json", ".git"],
        workspace_symbols: false,
        hover: true,
        definition: true,
        references: true,
        implementation: false,
        call_hierarchy: false,
        diagnostics: true,
        document_symbols: true,
        rename: true,
    },
    LanguageSpec {
        id: "php",
        name: "PHP",
        command: &["intelephense", "--stdio"],
        extensions: &["php"],
        markers: &["composer.json", ".git"],
        workspace_symbols: true,
        hover: true,
        definition: true,
        references: true,
        implementation: true,
        call_hierarchy: true,
        diagnostics: true,
        document_symbols: true,
        rename: true,
    },
    LanguageSpec {
        id: "zig",
        name: "Zig",
        command: &["zls"],
        extensions: &["zig", "zon"],
        markers: &["build.zig", ".git"],
        workspace_symbols: true,
        hover: true,
        definition: true,
        references: true,
        implementation: true,
        call_hierarchy: true,
        diagnostics: true,
        document_symbols: true,
        rename: true,
    },
    LanguageSpec {
        id: "elixir",
        name: "Elixir",
        command: &["elixir-ls"],
        extensions: &["ex", "exs"],
        markers: &["mix.exs", ".git"],
        workspace_symbols: true,
        hover: true,
        definition: true,
        references: true,
        implementation: true,
        call_hierarchy: false,
        diagnostics: true,
        document_symbols: true,
        rename: true,
    },
    LanguageSpec {
        id: "haskell",
        name: "Haskell",
        command: &["haskell-language-server-wrapper", "--lsp"],
        extensions: &["hs", "lhs"],
        markers: &["stack.yaml", "cabal.project", ".git"],
        workspace_symbols: true,
        hover: true,
        definition: true,
        references: true,
        implementation: true,
        call_hierarchy: true,
        diagnostics: true,
        document_symbols: true,
        rename: true,
    },
    LanguageSpec {
        id: "scala",
        name: "Scala",
        command: &["metals"],
        extensions: &["scala", "sbt", "sc"],
        markers: &["build.sbt", "build.sc", ".git"],
        workspace_symbols: true,
        hover: true,
        definition: true,
        references: true,
        implementation: true,
        call_hierarchy: true,
        diagnostics: true,
        document_symbols: true,
        rename: true,
    },
    LanguageSpec {
        id: "kotlin",
        name: "Kotlin",
        command: &["kotlin-language-server"],
        extensions: &["kt", "kts"],
        markers: &["build.gradle.kts", "settings.gradle.kts", ".git"],
        workspace_symbols: true,
        hover: true,
        definition: true,
        references: true,
        implementation: true,
        call_hierarchy: true,
        diagnostics: true,
        document_symbols: true,
        rename: true,
    },
    LanguageSpec {
        id: "svelte",
        name: "Svelte",
        command: &["svelteserver", "--stdio"],
        extensions: &["svelte"],
        markers: &["package.json", "svelte.config.js", ".git"],
        workspace_symbols: true,
        hover: true,
        definition: true,
        references: true,
        implementation: true,
        call_hierarchy: false,
        diagnostics: true,
        document_symbols: true,
        rename: true,
    },
    LanguageSpec {
        id: "vue",
        name: "Vue",
        command: &["vue-language-server", "--stdio"],
        extensions: &["vue"],
        markers: &["package.json", "vue.config.js", ".git"],
        workspace_symbols: true,
        hover: true,
        definition: true,
        references: true,
        implementation: true,
        call_hierarchy: false,
        diagnostics: true,
        document_symbols: true,
        rename: true,
    },
];
